### ISSUE TITLE
Your fofl12 is misusing the github issue system

### ISSUE THREAD

**Issue by notsuu** [Voxelstice/acg-roulette#7]
Plis ban from website him thank you

**Comment by Voxelstice** [comment]
Banned

**Comment by ghost** [comment]
Nowhat do you mena i found 4 secure vulnerables and htis is very bad and it needs to pbe fixefdm and dggksfdgjurgnelt,ay or iwajis will die

**Comment by notsuu** [comment]
Attach files by dragging & dropping, selecting or pasting them.

**Comment by vaariable** [comment]
Leave a comment

**Comment by notsuu** [comment]
Voxelstice/acg-roulette
### Create Issue

Title

Leave a comment (optional)
